name: "Build Zola for GitHub Pages"
description: "A simple GitHub Action for producing Zola build artifacts compatible with GitHub Pages"
inputs:
  zola-version:
    description: "Zola version to use."
    default: "0.17.1"
  root:
    description: "Directory where the source files reside."
    required: false
    default: ./
  output:
    description: "Output directory of the build. It cannot be the same as the source directory."
    required: false
    default: ./public
  drafts:
    description: "Include drafts when building the site."
    required: false
    default: false
  base-url:
    description: "Change the base URL of the website."
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Install Zola
      run: |
        curl -sLO 'https://github.com/getzola/zola/releases/download/v${{ inputs.ZOLA-VERSION }}/zola-v${{ inputs.ZOLA-VERSION }}-x86_64-unknown-linux-gnu.tar.gz'
        tar -xvzf zola-v${{ inputs.ZOLA-VERSION }}-x86_64-unknown-linux-gnu.tar.gz
        install -t $HOME/.local/bin -D zola
        rm zola
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Run Zola
      run: ${{ github.action_path }}/zola.sh
      id: zola
      env:
        # https://github.com/actions/runner/issues/665
        INPUT_ROOT: ${{ inputs.ROOT }}
        INPUT_OUTPUT: ${{ inputs.OUTPUT }}
        INPUT_DRAFTS: ${{ inputs.DRAFTS }}
        INPUT_BASE-URL: ${{ inputs.BASE-URL }}
      shell: bash
branding:
  icon: "zap"
  color: "gray-dark"
